services:
  LlmOcr:
    image: llmocr-local:latest
    build: .
    container_name: LlmOcr
    ports:
      - "8502:8502"  # 映射容器的8502端口到宿主机的8502端口
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 允许容器通过host.docker.internal访问宿主机
    restart: always